### ISSUE TITLE
[BUG] - Running Invoke-CCMCacheCleanup as SCCM package

### ISSUE THREAD

**Issue by mbradley73** [MEM-Zone/MEM.Zone#20]
**Describe the bug**
Trying to run the Invoke-CCMCacheCleanup script as a package in SCCM and getting a failure (message ID error 10006).

**To Reproduce**
This is the command I'm using:
%SystemRoot%\SysNative\WindowsPowerShell\v1.0\PowerShell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File Invoke-CCMCacheCleanup.ps1 -CacheType "Orphaned" -CleanupType "Tombstoned"

**Expected behavior**
For the script to clean complete with no errors and ccmcache be rid of orphaned packages.

**Comment by Ioan-Popovici** [comment]
Hi, 
You should not try to run it as a package because you are not installing anything. Please run it as a configuration baseline as specified. The error you specified is a generic error and you would need to check the execution logs to see what exactly went wrong.

If you run it as a detection script, you don't need a remediation script. You also need to suppress all output for this to work.

![CleanShot 2024-08-14 at 15 52 35@2x](https://github.com/user-attachments/assets/dfcb8b84-f526-4648-8c2c-a8efb9ceecad)

**Comment by mbradley73** [comment]
I often use package to run PowerShell scripts that don't need to install anything, so I was trying to do that same thing here. Being that the script requires more than just the file name, and needs various parameters, how do you do that in a baseline? I can only select a script to run in a CI, but don't see a way to set the parameters (like for orphaned content). 

Further troubleshooting this, running it manually on my machine, with this command line: .\Invoke-CCMCacheCleanup.ps1 -CacheType "Orphaned" -CleanupType "Tombstoned" , I get this error: Script initialization failed. Cannot validate argument on parameter 'ScriptSection'. The argument is null or empty.
Provide an argument that is not null or empty, and then try the command again.
At C:\clean\Invoke-CCMCacheCleanup.ps1:1766 char:5
+     Throw "Script initialization failed. $($PSItem.Exception.Message)

**Comment by Ioan-Popovici** [comment]
Yeah, I get it, but if there's no payload, why use packages?

In a CI you just have to change the default parameters. I'll make a blog post in the future.

Try the new version [here](https://github.com/MEM-Zone/MEM.Zone/tree/master/Scripts/PowerShell/Invoke-CCMCacheCleanup)

I don't know if it fixes it entirely, but it will fix the error you get so we can see what else is wrong.

The `Tombstoned` parameter should not be used with `Orphaned` because it doesn't make sense.
The orphaned cache is not supposed to be there because it has no links with the caching system.
I overlooked this when creating the script.

Please try with `Tombstoned` and `All` and report the result.

Thanks
Ioan

**Comment by mbradley73** [comment]
Sorry, I was going off the script comments that in the example appeared to include both of those conditions in the command.  I've now tried this: Invoke-CCMCacheCleanup.ps1 -CleanupType "Tombstoned" , and it resulted in no errors, but didn't remove anything either.  Are orphaned and tombstoned the same thing? Running just Invoke-CCMCacheCleanup.ps1 (which defaults to the All condition I think, right?), worked, deleting almost everything.  

Thank you for you assistance on this, it is much appreciated.

**Comment by Ioan-Popovici** [comment]
So there is a parameter issue.

Tombstoned means items that have passed the cache expiration date an can safely be deleted

Orphaned means wmi items that have no links on disk or disk items that have no links in wmi

I'll add a parameter check and explain these things better on the blog page.

Thanks
Ioan

**Comment by Life-of-Roy** [comment]
Looking for to the upcoming changes and implementing them in my environment.

**Comment by Ioan-Popovici** [comment]
Fixed, Closing issue.

**Comment by Life-of-Roy** [comment]
Hi Ioan, I grabbed v7.0 to try out but I'm still not seeing the results I was expecting.

Scenario #1 Results: Deleted all content from ccmcache.
 -CacheType "All" -CleanupType "Tombstoned"

Scenario #2 Results: No orphaned content found. The device has 89 folders in ccmcache with 35 of them being noted as orphaned by Right Click Tools. Changing the value of CacheType between All, Application and Update return expected values.
 -CacheType 'Orphaned' -CleanupType 'ListOnly'

I would be happy to evaluate any suggestions you would like to try.

**Comment by Ioan-Popovici** [comment]
I'll test the orphaned disk cache tomorrow. 

The orphaned WMI cache should work, you can test it easily by removing a folder from ccmcache folder and running the script with 'ListOnly'. It should display that cache entry as orphaned WMI cache.

**Comment by Life-of-Roy** [comment]
So the orphaned option is designed to match up wmi's list with the folders in ccmcache and then delete the wmi entry? I was under the impression that it would do a comparison but then purge the folders no longer needed in ccmcache.

**Comment by Ioan-Popovici** [comment]
That's what 'Orphaned' means 😄

Cache that has no relation in wmi and viceversa. This option is specifically for cleaning corrupted cache.

For what you need 'Automatic' can be used.

Read [my blog
post](https://mem.zone/tools/configmgr-client-cache-cleanup-tool/) to learn what's being deleted and the logic used.

What you need to know is that unless you use -DeletePinned or 'Referenced' cache that's still in use will not be deleted. The script is very clever only removing stuff that's not in use unless otherwise instructed.

**Comment by Ioan-Popovici** [comment]
Closing this as solved, please feel free to reopen this if you have more questions.
